(()=>{
const $=id=>document.getElementById(id),fmt=n=>n.toLocaleString('ja-JP'),sleep=ms=>new Promise(r=>setTimeout(r,ms)),ri=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,vib=p=>{try{navigator.vibrate&&navigator.vibrate(p)}catch{}};
const timerStyle=document.createElement('style');timerStyle.textContent='.timeAttack{margin-bottom:16px;padding:14px 18px;border-radius:18px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.09);display:flex;align-items:center;justify-content:space-between;gap:14px}.timeAttack.running{box-shadow:inset 0 0 28px rgba(96,165,250,.10)}.timeAttack.danger{box-shadow:0 0 22px rgba(239,68,68,.18),inset 0 0 28px rgba(239,68,68,.10)}.time-label{font-size:12px;letter-spacing:.16em;color:#94a3b8;font-weight:800}.time-sub{margin-top:4px;color:#cbd5e1;font-size:13px}.time-value{font-variant-numeric:tabular-nums;font-size:clamp(30px,7vw,46px);line-height:1;font-weight:1000;letter-spacing:.04em;white-space:nowrap}@media(max-width:760px){.timeAttack{padding:12px 14px}}';document.head.appendChild(timerStyle);
const ta=$('timeAttack');document.querySelector('.sub').textContent='10分でどこまで増やせるか。AT中はハズレるまで続く。';
const timerE=$('timerValue'),timeSub=$('timeSub'),bankE=$('bank'),potE=$('pot'),streakE=$('streak'),atView=$('atView'),atStat=$('atStat'),atBanner=$('atBanner'),atMain=$('atMain'),atSub=$('atSub'),atBadge=$('atBadge'),msg=$('message'),ticket=$('ticket'),stage=$('stage'),draw=$('drawBtn'),dbl=$('doubleBtn'),take=$('takeBtn'),reset=$('resetBtn'),hint=$('hintText'),hintSub=$('hintSub'),hintBox=$('hintBox'),aura=$('auraWrap'),historyList=$('historyList'),count=$('countdown'),overlay=$('overlay'),ovTitle=$('overlayTitle'),ovSub=$('overlaySub'),ovAmount=$('overlayAmount'),ovClose=$('overlayClose'),game=$('game'),particles=$('particles');
let bank=10000,pot=0,streak=0,locked=false,doubleChance=.5,currentHint=null,history=[],hidden='cold',hiddenTurns=8,at=false,atRate=0,atRound=0;
const DURATION=600000;let started=false,gameOver=false,endAt=0,timerId=null;
function timerText(ms){let s=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function renderTimer(ms=DURATION){timerE.textContent=timerText(ms);ta.classList.toggle('running',started&&!gameOver);ta.classList.toggle('danger',started&&!gameOver&&ms<=60000);timeSub.textContent=gameOver?'TIME UP':started?'10分タイムアタック進行中':'最初のくじでスタート'}
function startTimer(){if(started||gameOver)return;started=true;endAt=Date.now()+DURATION;renderTimer(DURATION);timerId=setInterval(tick,250)}
function tick(){if(!started||gameOver)return;let r=endAt-Date.now();if(r<=0)return finish();renderTimer(r)}
function finish(){if(gameOver)return;gameOver=true;if(timerId){clearInterval(timerId);timerId=null}renderTimer(0);let score=bank+pot,d=score-10000,delta=d>=0?`+${fmt(d)}`:fmt(d);locked=false;ticket.textContent='TIME UP';msg.textContent=`10分終了。最終スコアは ${fmt(score)}。`;vib([120,60,120,60,240]);show('good','TIME UP',`10分タイムアタック終了\n最終総コイン：${fmt(score)}\n初期10,000から：${delta}`,`SCORE ${fmt(score)}`);render()}
function renderAT(){if(at){atView.textContent='AT中';atStat.className='stat at-on';atBanner.classList.add('active');atMain.textContent=`AT中 (${atRound}回成功)`;atSub.textContent='無料抽選 / ハズレを引くとAT終了';atBadge.textContent='AT'}else{atView.textContent='通常状態';atStat.className='stat at-off';atBanner.classList.remove('active');atMain.textContent='ATはまだ始まっていません';atSub.textContent='通常時の内部状態は非表示。AT突入時だけ告知されます。';atBadge.textContent='—'}}
function render(){bankE.textContent=fmt(bank);potE.textContent=fmt(pot);streakE.textContent=streak;renderAT();draw.disabled=gameOver||locked||pot>0||(!at&&bank<100);dbl.disabled=gameOver||locked||pot<=0;take.disabled=gameOver||locked||pot<=0;draw.textContent=at?'AT中：無料で引く':'くじを引く'}
function show(kind,title,sub,amount=''){overlay.className='overlay show '+kind;ovTitle.textContent=title;ovSub.textContent=sub;ovAmount.textContent=amount}function hide(){overlay.className='overlay'}
function anim(c){ticket.classList.remove('draw','flip');void ticket.offsetWidth;ticket.classList.add(c)}function flash(win){stage.classList.remove('flash-win','flash-lose');void stage.offsetWidth;stage.classList.add(win?'flash-win':'flash-lose')}function shake(){game.classList.remove('shake-screen');void game.offsetWidth;game.classList.add('shake-screen')}
async function suspense(words){count.textContent='';for(const w of words){count.textContent=w;await sleep(280)}count.textContent=''}
function particlesInit(){particles.innerHTML='';for(let i=0;i<28;i++){let p=document.createElement('span');p.className='particle';let z=3+Math.random()*7;p.style.cssText=`left:${Math.random()*100}vw;bottom:${-20-Math.random()*60}px;width:${z}px;height:${z}px;animation-duration:${6+Math.random()*8}s;animation-delay:${Math.random()*8}s;opacity:${.35+Math.random()*.4}`;particles.appendChild(p)}}
function advanceHidden(){if(--hiddenTurns>0)return;if(hidden==='cold'){hidden='normal';hiddenTurns=ri(3,5)}else{hidden='cold';hiddenTurns=ri(7,10)}}function postAT(){hidden='cold';hiddenTurns=ri(8,11)}
function prize(){let r=Math.random()*100;if(at){if(r>=atRate*100)return 0;let h=Math.random()*100;return h<34?100:h<68?200:h<92?500:1000}if(hidden==='cold')return r<74?0:r<88?100:r<96?200:r<99?500:1000;return r<54?0:r<77?100:r<91?200:r<98?500:1000}
function mayAT(p){if(at||!p)return false;let x=hidden==='cold'?.05:.10;if(p>=500)x+=.08;if(p>=1000)x+=.08;return Math.random()<x}function startAT(){at=true;atRound=0;atRate=Math.random()<.5?.6:.8}function endAT(){at=false;atRate=0;atRound=0;postAT()}
function weighted(a){let t=a.reduce((s,x)=>s+x.w,0),r=Math.random()*t;for(const x of a){r-=x.w;if(r<=0)return x}return a.at(-1)}
function rollDouble(){let a=at?[.6,.7,.8]:hidden==='cold'?[.2,.3,.4,.5,.6]:[.3,.4,.5,.6,.7];return a[Math.floor(Math.random()*a.length)]}
function hintFor(c){if(c>=.8)return weighted([{text:'かなり良い気配がする',rank:4,w:52},{text:'今日は攻めてもよさそうだ',rank:3,w:26},{text:'悪くない流れだ',rank:2,w:14},{text:'嫌な予感がする…',rank:1,w:8}]);if(c>=.6)return weighted([{text:'かなり良い気配がする',rank:4,w:24},{text:'今日は攻めてもよさそうだ',rank:3,w:38},{text:'悪くない流れだ',rank:2,w:22},{text:'嫌な予感がする…',rank:1,w:16}]);if(c>=.45)return weighted([{text:'今日は攻めてもよさそうだ',rank:3,w:18},{text:'何とも言えない空気だ',rank:2,w:36},{text:'悪くない流れだ',rank:2,w:16},{text:'嫌な予感がする…',rank:1,w:18},{text:'かなり危険な気配だ',rank:0,w:12}]);if(c>=.3)return weighted([{text:'かなり良い気配がする',rank:4,w:9},{text:'今日は攻めてもよさそうだ',rank:3,w:14},{text:'何とも言えない空気だ',rank:2,w:22},{text:'嫌な予感がする…',rank:1,w:30},{text:'かなり危険な気配だ',rank:0,w:25}]);return weighted([{text:'かなり良い気配がする',rank:4,w:5},{text:'悪くない流れだ',rank:2,w:14},{text:'嫌な予感がする…',rank:1,w:32},{text:'かなり危険な気配だ',rank:0,w:49}])}
function renderAura(rank){aura.innerHTML='';for(let i=0;i<5;i++){let d=document.createElement('span');d.className='aura-dot';if(rank===2&&i<3)d.classList.add('neutral');else if(rank>=3&&i<rank+1)d.classList.add('on');else if(rank<2&&i<4-rank)d.classList.add('bad');aura.appendChild(d)}}
function newHint(){doubleChance=rollDouble();currentHint=hintFor(doubleChance);hint.textContent=currentHint.text;hintSub.textContent='示唆は内部状態をある程度反映。ただし確実ではありません。'+(at?'（AT中）':'');hintBox.className='hintbox rank'+currentHint.rank;renderAura(currentHint.rank)}function clearHint(){currentHint=null;hintBox.className='hintbox';hint.textContent='まだ示唆はありません';hintSub.textContent='当選すると次のダブルアップ示唆が表示されます。';renderAura(2)}
function hist(result,old,n,h){history.unshift({result,old,n,h:h?.text||'示唆なし'});history=history.slice(0,6);historyList.innerHTML='';for(const x of history){let s=document.createElement('span');s.className='tag';s.textContent=x.result==='win'?`成功 ${fmt(x.old)}→${fmt(x.n)} / 「${x.h}」`:`失敗 ${fmt(x.old)}→0 / 「${x.h}」`;historyList.appendChild(s)}}
async function drawGame(){if(gameOver||locked||pot>0)return;startTimer();if(bank<100&&!at)return;let usedAT=at;if(!usedAT)bank-=100;locked=true;streak=0;clearHint();anim('draw');ticket.textContent='?';msg.textContent=usedAT?'AT中！ 無料で抽選中…':'抽選中…';render();await suspense(usedAT?['AT','GO!']:['…','OPEN']);if(gameOver)return;let p=prize();if(!usedAT)advanceHidden();let entered=!usedAT&&mayAT(p);if(entered)startAT();pot=p;locked=false;if(!p){ticket.textContent='LOSE';msg.textContent=usedAT?'AT中ハズレ。AT終了。':'ハズレ。';flash(false);shake()}else{ticket.textContent=fmt(p);msg.textContent=`${fmt(p)}コイン当選。示唆を見て、攻めるか守るか。`;flash(true);if(p>=500)show('good','CHANCE','大きめの当選。ここから伸ばせるかも。',`${fmt(p)} COIN`);newHint()}if(entered){vib([80,40,120,40,180]);show('good','AT突入','ボーナスタイム突入！\nAT中は無料抽選。ハズレを引くまで継続します。','BONUS TIME');msg.textContent+=' さらにAT突入！'}else if(usedAT){if(p>0){atRound++;msg.textContent+=' AT継続！'}else{endAT();vib([220]);show('overlay-blue','AT終了','ハズレを引いたためAT終了。ここからは再び通常状態です。','END')}}render()}
async function doubleGame(){if(gameOver||pot<=0||locked)return;locked=true;let old=pot,h=currentHint,usedAT=at;msg.textContent='示唆確認… ダブルアップ抽選へ';ticket.textContent='???';anim('flip');render();await suspense(['3','2','1']);if(gameOver)return;let win=Math.random()<doubleChance;locked=false;if(win){pot*=2;streak++;ticket.textContent='DOUBLE!';vib([60,35,90]);msg.textContent=`成功！ 賞金は ${fmt(pot)} コイン。次の示唆も確認できます。`;hist('win',old,pot,h);flash(true);game.classList.add('glow-gold');setTimeout(()=>game.classList.remove('glow-gold'),700);if(pot>=2000||streak>=3)show('good','SUCCESS','ダブルアップ成功！',`${fmt(pot)} COIN`);newHint()}else{pot=0;streak=0;ticket.textContent='BUST';vib([180,70,180]);if(usedAT){endAT();msg.textContent='ダブルアップ失敗。今回の賞金は0になり、ATも終了しました。'}else msg.textContent='失敗。今回の賞金は0になりました。示唆は確実ではありません。';hist('lose',old,0,h);clearHint();flash(false);shake();usedAT?show('overlay-blue','AT終了','ダブルアップ失敗。今回の賞金は消滅し、ATも終了しました。','END'):show('bad','BUST','ダブルアップ失敗。今回の賞金は消滅しました。','0 COIN')}render()}
function takeGame(){if(gameOver||pot<=0||locked)return;let x=pot;bank+=pot;pot=0;streak=0;ticket.textContent='GET!';msg.textContent=`${fmt(x)}コインを受け取りました。`;clearHint();flash(true);show('green','GET!','賞金を安全に受け取りました。',`${fmt(x)} COIN`);render()}
function resetGame(){if(timerId){clearInterval(timerId);timerId=null}started=false;gameOver=false;endAt=0;bank=10000;pot=0;streak=0;locked=false;doubleChance=.5;currentHint=null;history=[];hidden='cold';hiddenTurns=8;at=false;atRate=0;atRound=0;historyList.innerHTML='<span class="tag">まだ記録なし</span>';ticket.textContent='LOTTERY';msg.textContent='100コインでくじを1枚引けます。';count.textContent='';clearHint();hide();renderTimer(DURATION);render()}
draw.addEventListener('click',drawGame);dbl.addEventListener('click',doubleGame);take.addEventListener('click',takeGame);reset.addEventListener('click',resetGame);ovClose.addEventListener('click',hide);overlay.addEventListener('click',e=>{if(e.target===overlay)hide()});particlesInit();clearHint();renderTimer(DURATION);render();
})();
